- name: Install npm
  apt:
     name: npm
     state: present
     update_cache: yes

- name: Dwnload Artifacts From Nexus
  include_tasks: download-nexus-artifacts.yml

- name: Setup SystemD Service
  include_tasks: setup-systemd.yml